### PR TITLE
Update tray status menus before menu is shown

### LINKED ISSUE #20: Store artifacts in CI

### LINKED ISSUE #31: Detailed status and tray menu status do not match
For some reason detailed status can recognize that my cluster is running while the rest of the tray does not get updated with this information. I am guessing this is also the reason why web console and oc login menu items are not enabled.

Screen Shot 2020-04-25 at 3 43 32 PM

### LINKED ISSUE #33: Stop multiple trays in the menu bar
The tray doesn't check if there's already a tray running and if one runs it repeatedly it puts multiple trays in the menu bar

### PR DESCRIPTION
**Pull request by anjannath**
Fixes #31 
Fixes #33
Fixes #20

### CODE REVIEW

**Comment by anjannath** [comment]
@gorkem Hi, can you please try out the build from this PR and verify if the issue #31 is fixed, you can find the artifacts at https://8-241065687-gh.circle-artifacts.com/0/crc-tray-macos.tar.gz 
(when extracted it'll create a directory named _out_ you'll find the tray app inside that dir)

You'll need to exit any running tray, and then start the new one you downloaded.

**Comment by gorkem** [comment]
This is not usable. Every time I try to open the menu I see a wheel that starts spinning and blocks any UI events that results on not being able to click on any menu items. Eventually when all the spinning is over the menu has the correct state but it basically makes tray unusable for any practical purposes.

**Comment by anjannath** [comment]
Ahh, my bad the fetching of the status from the daemon is being done in the main thread, which should be done in a background thread, that is the reason the UI is being blocked, will update the PR!

**Comment by gorkem** [comment]
Are you opening the detailed status window on the main thread too? Opening that one also makes the UI freeze. 

Now the UI freeze is gone and but status is not updated at all. I can not tell if it is because it is not trying to do anything or not blocking though.

**Comment by anjannath** [comment]
> Are you opening the detailed status window on the main thread too? Opening that one also makes the UI freeze.
> 
Yes, there is a small lag while opening the detailed status window, because it only shows up after the required information is fetched from the daemon and populated on the window, this can be improved, i'll look into it.

> Now the UI freeze is gone and but status is not updated at all. I can not tell if it is because it is not trying to do anything or not blocking though.

This should not be the case, i did try it this time and the status was getting updated, maybe @jsliacan can also try it on his mac and we can debug the issue.

**Comment by anjannath** [comment]
> Are you opening the detailed status window on the main thread too? Opening that one also makes the UI freeze.

Added 6925d0b00690c2e782d19f8dbfc15b03288fa157 for pushing the communication with the daemon for detailed status window to a background thread

**Pull request merged**
