### PR TITLE
Start the daemon from the tray

### PR DESCRIPTION
**Pull request by guillaumerose**
Requires https://github.com/code-ready/crc/pull/2156
Requires https://github.com/code-ready/crc/pull/2162

After this, we will have to change the macOS pkg to only ship /Application/CodeReady Containers.app and remove the launchd configuration of the daemon.

### CODE REVIEW

**Comment by guillaumerose** [comment]
(still adding more details in case of error)

**Comment by anjannath** [comment]
> After this, we will have to change the macOS pkg to only ship /Application/CodeReady Containers.app and remove the launchd configuration of the daemon.

And the `autostart-tray` config option also needs to be removed, the autostart control functionality we have to move to the tray

**Comment by guillaumerose** [comment]
Yes I think it's better if the tray handle it with a checkbox or so. The tray can call the daemon to add the proper files perhaps?

**Comment by guillaumerose** [comment]
I updated this PR with the exit code instead of the API to check if preflights are ok.

**Review by anjannath — APPROVED** [review]

**Pull request merged**
