### PR TITLE
Issue #11 Synchronize menu states

### PR DESCRIPTION
**Pull request by anjannath**
Update menu item states after each start/stop/delete
operation.

### CODE REVIEW

**Comment by gbraad** [comment]
Is it possible to use `(err != "")` instead of `!(err == "")`?

**Comment by gbraad** [comment]
On line 85 you have multiple values set. Can they be on new lines for each?

**Comment by gbraad** [comment]
"Is taking longer to start" is based on a measurable timeout?

**Comment by anjannath** [comment]
> On line 85 you have multiple values set. Can they be on new lines for each?
Actually that pattern is in a lot of places, that's where we are setting the new values (enabled, disabled) for the menu items, so its set from many places, i can later send another patch to fix it in all the other places, for now just here.

**Comment by anjannath** [comment]
> "Is taking longer to start" is based on a measurable timeout?

No, this will be shown after start has returned, that means after the initial 3 mins wait we have.

**Comment by gbraad** [comment]
Ok, so when 3 mins have passed. In that case acceptable ...

**Comment by gbraad** [comment]
Change line 171 didnt happen ;-)

**Comment by anjannath** [comment]
@gbraad I made all the requested changes, if any more changes are required we can create follow up issues, merging this to cut the release.

**Pull request merged**
